# Generated by Django 2.2.7 on 2021-01-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20210124_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='operator',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='products',
            name='numid',
            field=models.IntegerField(default=-1),
        ),
    ]
