# Generated by Django 2.2.7 on 2021-01-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_products_cardid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertlog',
            name='log',
        ),
        migrations.AddField(
            model_name='alertlog',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='alertlog',
            name='numid',
            field=models.CharField(default='', max_length=30),
        ),
    ]
