# Generated by Django 2.2.7 on 2021-01-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20210124_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertlog',
            name='name',
        ),
        migrations.AddField(
            model_name='alertlog',
            name='productname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='alertlog',
            name='productnumid',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='numid',
            field=models.IntegerField(default=-1),
        ),
    ]
