# Generated by Django 2.2.7 on 2021-03-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_park_sharelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='humidity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='park',
            name='lockstatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='park',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
    ]
