# Generated by Django 2.2.7 on 2021-03-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_auto_20210315_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='alertmail',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='status',
            name='deltamin',
            field=models.IntegerField(default=10),
        ),
    ]
