# Generated by Django 2.2.7 on 2021-03-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_auto_20210316_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='leavetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
