# Generated by Django 2.2.7 on 2021-04-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_auto_20210416_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='alertmail',
            field=models.CharField(default='', max_length=30),
        ),
    ]
