# Generated by Django 2.2.7 on 2021-05-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_auto_20210417_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
                ('productname', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='status',
            name='air',
        ),
        migrations.RemoveField(
            model_name='status',
            name='airset',
        ),
        migrations.RemoveField(
            model_name='status',
            name='airstatus',
        ),
        migrations.RemoveField(
            model_name='status',
            name='constatus',
        ),
        migrations.RemoveField(
            model_name='status',
            name='hum',
        ),
        migrations.RemoveField(
            model_name='status',
            name='humset',
        ),
        migrations.RemoveField(
            model_name='status',
            name='humstatus',
        ),
        migrations.RemoveField(
            model_name='status',
            name='lightset',
        ),
        migrations.RemoveField(
            model_name='status',
            name='lightstatus',
        ),
        migrations.RemoveField(
            model_name='status',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='status',
            name='tempset',
        ),
        migrations.RemoveField(
            model_name='status',
            name='tempstatus',
        ),
        migrations.AddField(
            model_name='status',
            name='alertstatus',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='status',
            name='ledset',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='status',
            name='ledstatus',
            field=models.IntegerField(default=-1),
        ),
    ]
