# Generated by Django 2.2.7 on 2021-05-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_remove_status_ledset'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='hum',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='status',
            name='temp',
            field=models.FloatField(default=0.0),
        ),
    ]
