# Generated by Django 2.2.7 on 2021-06-17 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='hum',
            new_name='lali',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='alertstatus',
            new_name='lalialertstatus',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='alerttime',
            new_name='lalialerttime',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='light',
            new_name='laliset',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='temp',
            new_name='yali',
        ),
        migrations.AddField(
            model_name='status',
            name='yalialertstatus',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='status',
            name='yalialerttime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='yaliset',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='status',
            name='zaoyin',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='status',
            name='zaoyinalertstatus',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='status',
            name='zaoyinalerttime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='zaoyinset',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='status',
            name='zhendong',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='status',
            name='zhendongalertstatus',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='status',
            name='zhendongalerttime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='zhendongset',
            field=models.FloatField(default=0.0),
        ),
    ]
