# Generated by Django 2.2.7 on 2021-06-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_auto_20210617_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('temptime', models.DateTimeField(auto_now=True)),
                ('yali', models.FloatField(default=0.0)),
                ('lali', models.FloatField(default=0.0)),
                ('zhendong', models.FloatField(default=0.0)),
                ('zaoyin', models.FloatField(default=0.0)),
            ],
        ),
    ]
