# Generated by Django 2.2.7 on 2021-01-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20201227_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('numid', models.IntegerField()),
                ('status', models.BooleanField()),
                ('addtime', models.DateTimeField()),
                ('outtime', models.DateTimeField()),
            ],
        ),
    ]
