# Generated by Django 2.2.7 on 2021-03-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_auto_20210316_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='comments',
            field=models.CharField(default='', max_length=30),
        ),
    ]
