# Generated by Django 2.2.7 on 2021-08-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_auto_20210627_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='data2',
        ),
        migrations.RemoveField(
            model_name='status',
            name='data2alertstatus',
        ),
        migrations.RemoveField(
            model_name='status',
            name='data2alerttime',
        ),
        migrations.RemoveField(
            model_name='status',
            name='data2set',
        ),
        migrations.RemoveField(
            model_name='status',
            name='data3',
        ),
        migrations.RemoveField(
            model_name='status',
            name='data3alertstatus',
        ),
        migrations.RemoveField(
            model_name='status',
            name='data3alerttime',
        ),
        migrations.RemoveField(
            model_name='status',
            name='data3set',
        ),
        migrations.RemoveField(
            model_name='status',
            name='data4',
        ),
        migrations.RemoveField(
            model_name='status',
            name='data4alertstatus',
        ),
        migrations.RemoveField(
            model_name='status',
            name='data4alerttime',
        ),
        migrations.RemoveField(
            model_name='status',
            name='data4set',
        ),
        migrations.RemoveField(
            model_name='status',
            name='data5',
        ),
        migrations.RemoveField(
            model_name='status',
            name='data5alertstatus',
        ),
        migrations.RemoveField(
            model_name='status',
            name='data5alerttime',
        ),
        migrations.RemoveField(
            model_name='status',
            name='data5set',
        ),
        migrations.AddField(
            model_name='info',
            name='comments',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='info',
            name='secret',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='info',
            name='userid',
            field=models.CharField(default='', max_length=30),
        ),
    ]
