# Generated by Django 2.2.7 on 2021-08-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_auto_20210802_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='data1',
        ),
    ]
