# Generated by Django 2.2.7 on 2021-08-02 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_remove_info_data1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
