# Generated by Django 2.2.7 on 2021-08-02 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0049_delete_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='userid',
        ),
    ]
