# Generated by Django 2.2.7 on 2021-03-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20210301_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='sharestatus',
            field=models.IntegerField(default=0),
        ),
    ]
