# Generated by Django 2.2.7 on 2021-04-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_status_autostatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='autostatus',
            new_name='constatus',
        ),
        migrations.RemoveField(
            model_name='status',
            name='ledstatus',
        ),
        migrations.RemoveField(
            model_name='status',
            name='windowclose',
        ),
        migrations.RemoveField(
            model_name='status',
            name='windowopen',
        ),
        migrations.RemoveField(
            model_name='status',
            name='windowstatus',
        ),
        migrations.AddField(
            model_name='status',
            name='humset',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='status',
            name='tempset',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='status',
            name='alertstatus',
            field=models.IntegerField(default=0),
        ),
    ]
