# Generated by Django 2.2.7 on 2021-05-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_auto_20210513_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='alertmail',
        ),
        migrations.AddField(
            model_name='info',
            name='alertmail',
            field=models.CharField(default='', max_length=30),
        ),
    ]
