# Generated by Django 2.2.7 on 2021-01-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
