# Generated by Django 2.2.7 on 2021-03-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_auto_20210316_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='alerttime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
