# Generated by Django 2.2.7 on 2021-04-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_status_alertmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='autostatus',
            field=models.IntegerField(default=0),
        ),
    ]
