document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'utf-8\' />");
document.writeln("		<link rel=\'stylesheet\' href=\'css/foot.css\' />");
// document.writeln("		<script src=\'js/jquery-3.2.1.min.js\'></script>");
document.writeln("	</head>");
document.writeln("		<footer>");
document.writeln("			<div class=\'contact\'>");
document.writeln("				<h2>Contact us</h2>");
document.writeln("				Address: 403/207 IRC，Beihang University, XueYuan Road No.37, HaiDian District, BeiJing, China");
document.writeln("				<br/>");
document.writeln("				Tel: 010-82315461");
document.writeln("			</div>");
document.writeln("			<div class=\'copyright\'>");
document.writeln("			Copyrights &copy; Multimedia Communication Computing (MC<sup>2</sup>) Lab");
document.writeln("			</div>");
document.writeln("			");
document.writeln("		</footer>");
document.writeln("</html>");
document.writeln("");