# Generated by Django 2.2.7 on 2021-03-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20210302_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='temptime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
