# Generated by Django 2.2.7 on 2021-04-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_status_alerttime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='humset',
            new_name='light',
        ),
        migrations.RemoveField(
            model_name='status',
            name='alertmail',
        ),
        migrations.RemoveField(
            model_name='status',
            name='manualstatus',
        ),
        migrations.RemoveField(
            model_name='status',
            name='period',
        ),
        migrations.RemoveField(
            model_name='status',
            name='setstatus',
        ),
        migrations.RemoveField(
            model_name='status',
            name='settime',
        ),
        migrations.RemoveField(
            model_name='status',
            name='tempset',
        ),
        migrations.AddField(
            model_name='status',
            name='alertstatus',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='status',
            name='ledstatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='lightset',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='status',
            name='windowclose',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='status',
            name='windowopen',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='status',
            name='windowstatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='status',
            name='alerttime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
