# Generated by Django 2.2.7 on 2021-03-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_park_temptime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('lon', models.FloatField(default=0.0)),
                ('lat', models.FloatField(default=0.0)),
                ('allnum', models.IntegerField(default=-1)),
                ('seatednum', models.IntegerField(default=-1)),
                ('temptime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AlertLog',
        ),
        migrations.DeleteModel(
            name='Data1',
        ),
        migrations.DeleteModel(
            name='Park',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Sharelog',
        ),
    ]
