# Generated by Django 2.2.7 on 2021-04-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_auto_20210417_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='alertstatus',
            new_name='humstatus',
        ),
        migrations.AddField(
            model_name='status',
            name='lightstatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='tempstatus',
            field=models.IntegerField(default=0),
        ),
    ]
